title = "Going Minimal - The Joy of Less "
baseurl             = ""
relativeURLs        = true
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-GB"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Ben Hughes"
pygmentsuseclasses  = true
disqusshortname     = "goingminimal" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"
theme               = "cocoa"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "Going Minmal"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Don't panic"
email        = "bwghughes@gmail.com"
faviconfile  = "img/leaf.ico"
github       = "//github.com/bwghughes"
highlightjs  = true
lang         = "en"
linkedin     = "//linkedin.com/in/bwghughes"
twitter      = "//twitter.com/bwghughes"

# gravatar             = ""     # do not use in the same time as avatar
# avatar               = ""     # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"] # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
